# Generated by Django 3.0.9 on 2020-08-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200806_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.Field(primary_key=True, serialize=False),
        ),
    ]
