# Generated by Django 3.0.9 on 2020-08-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200807_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.Field(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(default='Author Name', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.Employee'),
        ),
    ]
