# Generated by Django 3.0.9 on 2020-08-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200807_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(default='D', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.Employee'),
        ),
    ]
